//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIST_AOI.wsCAMX {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://camx.rpc.cogiscan.com/", ConfigurationName="wsCAMX.CAMXMessageBroker")]
    public interface CAMXMessageBroker {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/subscribeForEventRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/subscribeForEventResponse")]
        HIST_AOI.wsCAMX.subscribeForEventResponse subscribeForEvent(HIST_AOI.wsCAMX.subscribeForEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/subscribeForEventRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/subscribeForEventResponse")]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.subscribeForEventResponse> subscribeForEventAsync(HIST_AOI.wsCAMX.subscribeForEventRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/acknowledgeEventsRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/acknowledgeEventsResponse")]
        HIST_AOI.wsCAMX.acknowledgeEventsResponse acknowledgeEvents(HIST_AOI.wsCAMX.acknowledgeEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/acknowledgeEventsRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/acknowledgeEventsResponse")]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.acknowledgeEventsResponse> acknowledgeEventsAsync(HIST_AOI.wsCAMX.acknowledgeEventsRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/logoutRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/logoutResponse")]
        HIST_AOI.wsCAMX.logoutResponse logout(HIST_AOI.wsCAMX.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/logoutRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/logoutResponse")]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.logoutResponse> logoutAsync(HIST_AOI.wsCAMX.logoutRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/waitForEventRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/waitForEventResponse")]
        HIST_AOI.wsCAMX.waitForEventResponse waitForEvent(HIST_AOI.wsCAMX.waitForEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/waitForEventRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/waitForEventResponse")]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.waitForEventResponse> waitForEventAsync(HIST_AOI.wsCAMX.waitForEventRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/postEventsRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/postEventsResponse")]
        HIST_AOI.wsCAMX.postEventsResponse postEvents(HIST_AOI.wsCAMX.postEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/postEventsRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/postEventsResponse")]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.postEventsResponse> postEventsAsync(HIST_AOI.wsCAMX.postEventsRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/pullEventsRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/pullEventsResponse")]
        HIST_AOI.wsCAMX.pullEventsResponse pullEvents(HIST_AOI.wsCAMX.pullEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/pullEventsRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/pullEventsResponse")]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.pullEventsResponse> pullEventsAsync(HIST_AOI.wsCAMX.pullEventsRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/loginRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/loginResponse")]
        HIST_AOI.wsCAMX.loginResponse login(HIST_AOI.wsCAMX.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://camx.rpc.cogiscan.com/CAMXMessageBroker/loginRequest", ReplyAction="http://camx.rpc.cogiscan.com/CAMXMessageBroker/loginResponse")]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.loginResponse> loginAsync(HIST_AOI.wsCAMX.loginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class subscribeForEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="subscribeForEvent", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.subscribeForEventRequestBody Body;
        
        public subscribeForEventRequest() {
        }
        
        public subscribeForEventRequest(HIST_AOI.wsCAMX.subscribeForEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class subscribeForEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public subscribeForEventRequestBody() {
        }
        
        public subscribeForEventRequestBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class subscribeForEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="subscribeForEventResponse", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.subscribeForEventResponseBody Body;
        
        public subscribeForEventResponse() {
        }
        
        public subscribeForEventResponse(HIST_AOI.wsCAMX.subscribeForEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class subscribeForEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public subscribeForEventResponseBody() {
        }
        
        public subscribeForEventResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class acknowledgeEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="acknowledgeEvents", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.acknowledgeEventsRequestBody Body;
        
        public acknowledgeEventsRequest() {
        }
        
        public acknowledgeEventsRequest(HIST_AOI.wsCAMX.acknowledgeEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class acknowledgeEventsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public acknowledgeEventsRequestBody() {
        }
        
        public acknowledgeEventsRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class acknowledgeEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="acknowledgeEventsResponse", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.acknowledgeEventsResponseBody Body;
        
        public acknowledgeEventsResponse() {
        }
        
        public acknowledgeEventsResponse(HIST_AOI.wsCAMX.acknowledgeEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class acknowledgeEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public acknowledgeEventsResponseBody() {
        }
        
        public acknowledgeEventsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logout", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.logoutRequestBody Body;
        
        public logoutRequest() {
        }
        
        public logoutRequest(HIST_AOI.wsCAMX.logoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class logoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public logoutRequestBody() {
        }
        
        public logoutRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutResponse", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.logoutResponseBody Body;
        
        public logoutResponse() {
        }
        
        public logoutResponse(HIST_AOI.wsCAMX.logoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class logoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public logoutResponseBody() {
        }
        
        public logoutResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class waitForEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="waitForEvent", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.waitForEventRequestBody Body;
        
        public waitForEventRequest() {
        }
        
        public waitForEventRequest(HIST_AOI.wsCAMX.waitForEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class waitForEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public waitForEventRequestBody() {
        }
        
        public waitForEventRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class waitForEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="waitForEventResponse", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.waitForEventResponseBody Body;
        
        public waitForEventResponse() {
        }
        
        public waitForEventResponse(HIST_AOI.wsCAMX.waitForEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class waitForEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public waitForEventResponseBody() {
        }
        
        public waitForEventResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="postEvents", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.postEventsRequestBody Body;
        
        public postEventsRequest() {
        }
        
        public postEventsRequest(HIST_AOI.wsCAMX.postEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class postEventsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public postEventsRequestBody() {
        }
        
        public postEventsRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="postEventsResponse", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.postEventsResponseBody Body;
        
        public postEventsResponse() {
        }
        
        public postEventsResponse(HIST_AOI.wsCAMX.postEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class postEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public postEventsResponseBody() {
        }
        
        public postEventsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pullEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pullEvents", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.pullEventsRequestBody Body;
        
        public pullEventsRequest() {
        }
        
        public pullEventsRequest(HIST_AOI.wsCAMX.pullEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class pullEventsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public pullEventsRequestBody() {
        }
        
        public pullEventsRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pullEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pullEventsResponse", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.pullEventsResponseBody Body;
        
        public pullEventsResponse() {
        }
        
        public pullEventsResponse(HIST_AOI.wsCAMX.pullEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class pullEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public pullEventsResponseBody() {
        }
        
        public pullEventsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(HIST_AOI.wsCAMX.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://camx.rpc.cogiscan.com/", Order=0)]
        public HIST_AOI.wsCAMX.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(HIST_AOI.wsCAMX.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CAMXMessageBrokerChannel : HIST_AOI.wsCAMX.CAMXMessageBroker, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CAMXMessageBrokerClient : System.ServiceModel.ClientBase<HIST_AOI.wsCAMX.CAMXMessageBroker>, HIST_AOI.wsCAMX.CAMXMessageBroker {
        
        public CAMXMessageBrokerClient() {
        }
        
        public CAMXMessageBrokerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CAMXMessageBrokerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAMXMessageBrokerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAMXMessageBrokerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HIST_AOI.wsCAMX.subscribeForEventResponse HIST_AOI.wsCAMX.CAMXMessageBroker.subscribeForEvent(HIST_AOI.wsCAMX.subscribeForEventRequest request) {
            return base.Channel.subscribeForEvent(request);
        }
        
        public string subscribeForEvent(string arg0, string arg1, string arg2) {
            HIST_AOI.wsCAMX.subscribeForEventRequest inValue = new HIST_AOI.wsCAMX.subscribeForEventRequest();
            inValue.Body = new HIST_AOI.wsCAMX.subscribeForEventRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            HIST_AOI.wsCAMX.subscribeForEventResponse retVal = ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).subscribeForEvent(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.subscribeForEventResponse> HIST_AOI.wsCAMX.CAMXMessageBroker.subscribeForEventAsync(HIST_AOI.wsCAMX.subscribeForEventRequest request) {
            return base.Channel.subscribeForEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<HIST_AOI.wsCAMX.subscribeForEventResponse> subscribeForEventAsync(string arg0, string arg1, string arg2) {
            HIST_AOI.wsCAMX.subscribeForEventRequest inValue = new HIST_AOI.wsCAMX.subscribeForEventRequest();
            inValue.Body = new HIST_AOI.wsCAMX.subscribeForEventRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).subscribeForEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HIST_AOI.wsCAMX.acknowledgeEventsResponse HIST_AOI.wsCAMX.CAMXMessageBroker.acknowledgeEvents(HIST_AOI.wsCAMX.acknowledgeEventsRequest request) {
            return base.Channel.acknowledgeEvents(request);
        }
        
        public string acknowledgeEvents(string arg0, string arg1) {
            HIST_AOI.wsCAMX.acknowledgeEventsRequest inValue = new HIST_AOI.wsCAMX.acknowledgeEventsRequest();
            inValue.Body = new HIST_AOI.wsCAMX.acknowledgeEventsRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            HIST_AOI.wsCAMX.acknowledgeEventsResponse retVal = ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).acknowledgeEvents(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.acknowledgeEventsResponse> HIST_AOI.wsCAMX.CAMXMessageBroker.acknowledgeEventsAsync(HIST_AOI.wsCAMX.acknowledgeEventsRequest request) {
            return base.Channel.acknowledgeEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HIST_AOI.wsCAMX.acknowledgeEventsResponse> acknowledgeEventsAsync(string arg0, string arg1) {
            HIST_AOI.wsCAMX.acknowledgeEventsRequest inValue = new HIST_AOI.wsCAMX.acknowledgeEventsRequest();
            inValue.Body = new HIST_AOI.wsCAMX.acknowledgeEventsRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).acknowledgeEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HIST_AOI.wsCAMX.logoutResponse HIST_AOI.wsCAMX.CAMXMessageBroker.logout(HIST_AOI.wsCAMX.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public string logout(string arg0) {
            HIST_AOI.wsCAMX.logoutRequest inValue = new HIST_AOI.wsCAMX.logoutRequest();
            inValue.Body = new HIST_AOI.wsCAMX.logoutRequestBody();
            inValue.Body.arg0 = arg0;
            HIST_AOI.wsCAMX.logoutResponse retVal = ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).logout(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.logoutResponse> HIST_AOI.wsCAMX.CAMXMessageBroker.logoutAsync(HIST_AOI.wsCAMX.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<HIST_AOI.wsCAMX.logoutResponse> logoutAsync(string arg0) {
            HIST_AOI.wsCAMX.logoutRequest inValue = new HIST_AOI.wsCAMX.logoutRequest();
            inValue.Body = new HIST_AOI.wsCAMX.logoutRequestBody();
            inValue.Body.arg0 = arg0;
            return ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HIST_AOI.wsCAMX.waitForEventResponse HIST_AOI.wsCAMX.CAMXMessageBroker.waitForEvent(HIST_AOI.wsCAMX.waitForEventRequest request) {
            return base.Channel.waitForEvent(request);
        }
        
        public string waitForEvent(string arg0) {
            HIST_AOI.wsCAMX.waitForEventRequest inValue = new HIST_AOI.wsCAMX.waitForEventRequest();
            inValue.Body = new HIST_AOI.wsCAMX.waitForEventRequestBody();
            inValue.Body.arg0 = arg0;
            HIST_AOI.wsCAMX.waitForEventResponse retVal = ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).waitForEvent(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.waitForEventResponse> HIST_AOI.wsCAMX.CAMXMessageBroker.waitForEventAsync(HIST_AOI.wsCAMX.waitForEventRequest request) {
            return base.Channel.waitForEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<HIST_AOI.wsCAMX.waitForEventResponse> waitForEventAsync(string arg0) {
            HIST_AOI.wsCAMX.waitForEventRequest inValue = new HIST_AOI.wsCAMX.waitForEventRequest();
            inValue.Body = new HIST_AOI.wsCAMX.waitForEventRequestBody();
            inValue.Body.arg0 = arg0;
            return ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).waitForEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HIST_AOI.wsCAMX.postEventsResponse HIST_AOI.wsCAMX.CAMXMessageBroker.postEvents(HIST_AOI.wsCAMX.postEventsRequest request) {
            return base.Channel.postEvents(request);
        }
        
        public string postEvents(string arg0, string arg1) {
            HIST_AOI.wsCAMX.postEventsRequest inValue = new HIST_AOI.wsCAMX.postEventsRequest();
            inValue.Body = new HIST_AOI.wsCAMX.postEventsRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            HIST_AOI.wsCAMX.postEventsResponse retVal = ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).postEvents(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.postEventsResponse> HIST_AOI.wsCAMX.CAMXMessageBroker.postEventsAsync(HIST_AOI.wsCAMX.postEventsRequest request) {
            return base.Channel.postEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HIST_AOI.wsCAMX.postEventsResponse> postEventsAsync(string arg0, string arg1) {
            HIST_AOI.wsCAMX.postEventsRequest inValue = new HIST_AOI.wsCAMX.postEventsRequest();
            inValue.Body = new HIST_AOI.wsCAMX.postEventsRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).postEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HIST_AOI.wsCAMX.pullEventsResponse HIST_AOI.wsCAMX.CAMXMessageBroker.pullEvents(HIST_AOI.wsCAMX.pullEventsRequest request) {
            return base.Channel.pullEvents(request);
        }
        
        public string pullEvents(string arg0) {
            HIST_AOI.wsCAMX.pullEventsRequest inValue = new HIST_AOI.wsCAMX.pullEventsRequest();
            inValue.Body = new HIST_AOI.wsCAMX.pullEventsRequestBody();
            inValue.Body.arg0 = arg0;
            HIST_AOI.wsCAMX.pullEventsResponse retVal = ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).pullEvents(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.pullEventsResponse> HIST_AOI.wsCAMX.CAMXMessageBroker.pullEventsAsync(HIST_AOI.wsCAMX.pullEventsRequest request) {
            return base.Channel.pullEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HIST_AOI.wsCAMX.pullEventsResponse> pullEventsAsync(string arg0) {
            HIST_AOI.wsCAMX.pullEventsRequest inValue = new HIST_AOI.wsCAMX.pullEventsRequest();
            inValue.Body = new HIST_AOI.wsCAMX.pullEventsRequestBody();
            inValue.Body.arg0 = arg0;
            return ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).pullEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HIST_AOI.wsCAMX.loginResponse HIST_AOI.wsCAMX.CAMXMessageBroker.login(HIST_AOI.wsCAMX.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string arg0, string arg1) {
            HIST_AOI.wsCAMX.loginRequest inValue = new HIST_AOI.wsCAMX.loginRequest();
            inValue.Body = new HIST_AOI.wsCAMX.loginRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            HIST_AOI.wsCAMX.loginResponse retVal = ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HIST_AOI.wsCAMX.loginResponse> HIST_AOI.wsCAMX.CAMXMessageBroker.loginAsync(HIST_AOI.wsCAMX.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<HIST_AOI.wsCAMX.loginResponse> loginAsync(string arg0, string arg1) {
            HIST_AOI.wsCAMX.loginRequest inValue = new HIST_AOI.wsCAMX.loginRequest();
            inValue.Body = new HIST_AOI.wsCAMX.loginRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((HIST_AOI.wsCAMX.CAMXMessageBroker)(this)).loginAsync(inValue);
        }
    }
}
