//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIST_AOI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_history_t
    {
        public int se_id { get; set; }
        public string se_panel_id { get; set; }
        public string se_test_result { get; set; }
        public string se_line { get; set; }
        public string se_message { get; set; }
        public System.DateTime se_date { get; set; }
    }
}
