//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIST_AOI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AOIPCB
    {
        public System.Guid PCBGUID { get; set; }
        public Nullable<long> PCBID { get; set; }
        public string MachineID { get; set; }
        public string MachineIP { get; set; }
        public Nullable<System.Guid> JobGUID { get; set; }
        public string JobFileIDLocal { get; set; }
        public string JobFileIDShare { get; set; }
        public string JobFileShareDir { get; set; }
        public string Lot { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string UserID { get; set; }
        public Nullable<int> PCBResultBefore { get; set; }
        public Nullable<int> PCBResultAfter { get; set; }
        public Nullable<int> PCBRepair { get; set; }
        public string BarCode { get; set; }
        public string ALLBarCode { get; set; }
        public Nullable<int> PCBTotalComp { get; set; }
        public Nullable<int> PCBTotalInsp { get; set; }
        public Nullable<int> ArrayCnt { get; set; }
        public Nullable<int> SaveDone { get; set; }
        public Nullable<int> Checksum { get; set; }
        public string TB { get; set; }
        public string ResultDBName { get; set; }
        public string ImageDBName { get; set; }
        public Nullable<double> FieldVersion { get; set; }
        public string PCBComment { get; set; }
        public string PCBModel { get; set; }
        public Nullable<int> LotType { get; set; }
        public Nullable<int> SaveMode { get; set; }
        public Nullable<System.DateTime> RepairStartDateTime { get; set; }
        public Nullable<System.DateTime> RepairEndDateTime { get; set; }
        public Nullable<System.DateTime> ReviewStartDateTime { get; set; }
        public Nullable<System.DateTime> ReviewEndDateTime { get; set; }
        public string RepairUserID { get; set; }
        public string ReviewUserID { get; set; }
        public Nullable<int> PCBResultRepair { get; set; }
        public Nullable<int> PCBIndexByModel { get; set; }
        public Nullable<int> Lane { get; set; }
        public string MesInterface { get; set; }
        public Nullable<int> TeachingArrayCnt { get; set; }
        public Nullable<int> MesUse { get; set; }
        public Nullable<int> ScrapCode { get; set; }
        public Nullable<int> PCBResultVersion { get; set; }
        public Nullable<int> ExistLinkData { get; set; }
        public Nullable<int> LinkResult { get; set; }
        public Nullable<int> TeachingCompCnt { get; set; }
        public string TagSet { get; set; }
        public Nullable<int> InspError { get; set; }
        public Nullable<int> DispReviewUpperNGCnt { get; set; }
        public string FlipperKey { get; set; }
        public Nullable<int> IsCheckTheChecker { get; set; }
        public string CTCMasterPCB { get; set; }
        public string CTCSubPCBDisplayedName { get; set; }
    }
}
